//
// Created by mpait on 21/11/2023.
//

#ifndef GRAPHTHEORYPROJECT_GROUP2_LOCALSEARCHHEURISTIC_H
#define GRAPHTHEORYPROJECT_GROUP2_LOCALSEARCHHEURISTIC_H


class LocalSearchHeuristic {

};


#endif //GRAPHTHEORYPROJECT_GROUP2_LOCALSEARCHHEURISTIC_H
