//
// Created by mpait on 21/11/2023.
//

#ifndef GRAPHTHEORYPROJECT_GROUP2_CONSTRUCTIVEHEURISTIC_H
#define GRAPHTHEORYPROJECT_GROUP2_CONSTRUCTIVEHEURISTIC_H


class ConstructiveHeuristic {

};


#endif //GRAPHTHEORYPROJECT_GROUP2_CONSTRUCTIVEHEURISTIC_H
