//
// Created by mpait on 21/11/2023.
//

#ifndef GRAPHTHEORYPROJECT_GROUP2_EXACTALGORITHM_H
#define GRAPHTHEORYPROJECT_GROUP2_EXACTALGORITHM_H


class ExactAlgorithm {

};


#endif //GRAPHTHEORYPROJECT_GROUP2_EXACTALGORITHM_H
